#!/usr/bin/env python3
"""
new-app.py — Scaffold a new Austin map app from the templateapp.

Usage:
    python scripts/new-app.py --name coffee-shops

What it does:
    1. Copies apps/templateapp/ → apps/{name}/
    2. Removes the placeholder data.geojson (Claude will generate a real one)
    3. Rewrites config.js to a blank stub with instructions
    4. Overlay paths already point to ../../_shared/ in the copied app.js

After running, give Claude:
    - The dataset topic
    - The Austin Open Data Portal URL (if cross-referencing health scores etc.)
    - Which fields to show in filters, table columns, and popups

Claude will then generate config.js and data.geojson and commit them.
"""

import argparse
import os
import shutil
import re
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATE_DIR = os.path.join(REPO_ROOT, "apps", "templateapp")

# Files that should NOT be copied from the template (Claude generates these fresh)
SKIP_FILES = {"data.geojson", "CLAUDE.md", "clauderemembertoalwayspushtomain.md"}


def main():
    parser = argparse.ArgumentParser(description="Scaffold a new map app from templateapp")
    parser.add_argument("--name", required=True, help="App folder name slug, e.g. coffee-shops")
    args = parser.parse_args()

    name = args.name.strip().lower()
    if not re.match(r"^[a-z0-9-]+$", name):
        print(f"ERROR: --name must be lowercase letters, numbers, and hyphens only. Got: {name}")
        sys.exit(1)

    dest_dir = os.path.join(REPO_ROOT, "apps", name)

    if os.path.exists(dest_dir):
        print(f"ERROR: apps/{name}/ already exists. Choose a different name or delete it first.")
        sys.exit(1)

    print(f"Scaffolding apps/{name}/ from apps/templateapp/ ...")

    # Copy template, skipping unwanted files
    os.makedirs(dest_dir)
    for item in os.listdir(TEMPLATE_DIR):
        if item in SKIP_FILES:
            continue
        src = os.path.join(TEMPLATE_DIR, item)
        dst = os.path.join(dest_dir, item)
        if os.path.isfile(src):
            shutil.copy2(src, dst)

    # Write a stub config.js with clear instructions for Claude
    stub_config = (
        "// ============================================================\n"
        f"// CONFIG for: {name}\n"
        "// Generated by scripts/new-app.py — Claude will fill this in.\n"
        "// ============================================================\n"
        "const CONFIG = {\n"
        '  title: "",        // e.g. "Coffee Shops"\n'
        '  eyebrow: "",      // e.g. "Austin Metro"\n'
        "\n"
        "  center: [-97.743, 30.267],   // Austin city center\n"
        "  zoom: 12,\n"
        "  pitch: 45,\n"
        "  bearing: -15,\n"
        '  markerColor: "#e63946",\n'
        "\n"
        '  overlayLabel: "Zip Codes",\n'
        '  overlayColorProperty: "zipcode",\n'
        '  overlay2Label: "Flood Zone",\n'
        '  overlay2ColorProperty: "flood_zone",\n'
        '  overlay3Label: "City Council",\n'
        '  overlay3ColorProperty: "district_name",\n'
        "\n"
        '  nameField: "name",\n'
        "\n"
        "  filters: [\n"
        '    // { property: "kind", label: "Type" }\n'
        "  ],\n"
        "\n"
        "  columns: [\n"
        '    // { property: "name", header: "Name" }\n'
        "  ],\n"
        "\n"
        "  popupFields: [\n"
        '    // { property: "address", label: "Address" }\n'
        "  ]\n"
        "};\n"
    )
    with open(os.path.join(dest_dir, "config.js"), "w") as f:
        f.write(stub_config)

    # Write an empty data.geojson placeholder
    empty_geojson = '{"type":"FeatureCollection","features":[]}\n'
    with open(os.path.join(dest_dir, "data.geojson"), "w") as f:
        f.write(empty_geojson)

    print(f"Done. apps/{name}/ created with {len(os.listdir(dest_dir))} files.")
    print()
    print("Next steps:")
    print(f"  1. Tell Claude: 'Build data for apps/{name}/ — topic: {name}'")
    print(f"     Provide: Austin Open Data URL (if any), fields to show, filter dropdowns")
    print(f"  2. Claude will generate data.geojson and fill in config.js")
    print(f"  3. Claude will commit and push — live at anatomy.city/apps/{name}/")


if __name__ == "__main__":
    main()
